TUNING.WETZEL_HEALTH = 175
TUNING.WETZEL_HUNGER = 150
TUNING.WETZEL_SANITY = 200

TUNING.GAMEMODE_STARTING_ITEMS.DEFAULT.WETZEL = {
	"nightmarefuel",
	"nightmarefuel",
	"nightmarefuel",
	"nightmarefuel",
	"nightmarefuel",
}

TUNING.WETZEL = 
{
	REMOVE_ITEM_CHANGE = 0.75,
	ITEM_PERISH_AMOUNT = .34,

	FOOD_PERISH_TIME = TUNING.TOTAL_DAY_TIME * 0.25,

	SHADOWS_DAMAGE = -10,

	FEATHER_LIGHT_DURATION = TUNING.TOTAL_DAY_TIME * 0.75,
	FEATHER_LIGHT_TEMP = 35,
	FEATHER_LIGHT_USES = 10,
	FEATHER_LIGHT_COST = 0.25,

	FEATHER_FREEZE_RANGE = 15,
	FEATHER_FREEZE = 10,
	FEATHER_FREEZE_PLAYER = 5,
	FEATHER_FREEZE_USES = 2,
	FEATHER_FREEZE_COST = 0.75,

	FEATHER_HEALING_RANGE = 15,
	FEATHER_HEALING_MAX = 40,
	FEATHER_HEALING_MIN = 10,
	FEATHER_HEALING_PER_PLAYER = -5,
	FEATHER_HEALING_USES = 5,
	FEATHER_HEALING_COST = 0.25,

	FEATHER_TELEPORT_DURATION = 10,
	FEATHER_TELEPORT_SPEED_MULT = 2.5,
	FEATHER_TELEPORT_USES = 2,
	TELEPORT_TELEPORT_COST = 0.75,

	DRAW_USES = .1,

	PUDDLE_SANITY = 0.2,
	PUDDLE_SANITY_AMOUNT = 10,
	SANITY_PENALTY_DURATION = TUNING.TOTAL_DAY_TIME * 0.5,
	PUDDLE_DURATION = TUNING.TOTAL_DAY_TIME * 0.25,

	TELEPORT_RANGE = 20,

	BOTTLE_USES = 10,
	BRUSH_USES = 10,

	FOOD_SANITY_MULT = 0,
}

-- Fox: Constants go here BECAUSE I WANT SO
WETZEL_INK_COLOUR = {41/255, 28/255, 58/255, 1}

-- Fox: Those "enums" are used for networking
WETZEL_FEATHERS = {
	BLACK = 0,
	RED = 1,
	WHITE = 2,
	YELLOW = 3,
}

WETZEL_FEATHERS_IDS = table.invert(WETZEL_FEATHERS)

WETZEL_FEATHERS_COLOURS = {
	[WETZEL_FEATHERS.BLACK] = WETZEL_INK_COLOUR,
	[WETZEL_FEATHERS.RED] = {1, 0, 0},
	[WETZEL_FEATHERS.WHITE] = {1, 1, 1},
	[WETZEL_FEATHERS.YELLOW] = {1, 1, 0},
}