--Generated by Util/Dynify.py
return {
	Asset("DYNAMIC_ANIM", "anim/dynamic/wayne_feather_black_royal.zip"),
	Asset("PKGREF", "anim/dynamic/wayne_feather_black_royal.dyn"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/wayne_feather_red_royal.zip"),
	Asset("PKGREF", "anim/dynamic/wayne_feather_red_royal.dyn"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/wayne_feather_white_royal.zip"),
	Asset("PKGREF", "anim/dynamic/wayne_feather_white_royal.dyn"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/wayne_feather_yellow_royal.zip"),
	Asset("PKGREF", "anim/dynamic/wayne_feather_yellow_royal.dyn"),
}
